In [ ]:
# time complexity O(n)

def sum_array(arr): # arr has 10 elements i.e 1,2,3,4,5,6,7,8,9,10
    sum = 0 # intial
    for num in arr:
        sum += num # sum = sum + num
    return sum

can have duplicate items.

mutable.

ordered.

index based(starts from 0).

can store mixed data types and other lists too.

In [9]:
# listx = [1,1,2,3,4,4,5,6,7,8,9,9,0,1]

Creating a list

In [5]:
# square brackets []

a = [1,2,3,4,5,6] # list of integers
b = ["hello", "dush"] # list of strings
c = [1, 'bye', 3.14, False] # mixed data types
print(a)
print(b)
print(c)

[1, 2, 3, 4, 5, 6]
['hello', 'dush']
[1, 'bye', 3.14, False]


In [13]:
# list() constructor

a1 = list((4,5,6, 'meta', 6.9))
print(a1)

b1 = list("bonthu")
print(b1)

TypeError: 'list' object is not callable

In [7]:
# repeated elements

a11 = [2] * 5
b11 = [0] * 7
c11 = ['python'] * 3

print(a11)
print(b11)
print(c11)

[2, 2, 2, 2, 2]
[0, 0, 0, 0, 0, 0, 0]
['python', 'python', 'python']


In [11]:
# accessing list elements

aa = [10, 20, 30, 40, 50, 60]
print(aa[0])
print(aa[-1])
print(aa[-4])
print(aa[1:4]) # slicing

10
60
30
[20, 30, 40]


Adding elements into list


1. append()

2. extend()

3. insert()

4. clear()

In [ ]:
new = [] # empty list

new.append(10)
print("after append(10):", new)

new.insert(0, 5)
print("after insert(0, 5):", new)

new.extend([15,20,25,30])
print("after extend([15,20,25,30]):", new)

new.clear()
print("after clear():", new)

after append(10): [10]
after insert(0, 5): [5, 10]
after extend([15,20,25,30]): [5, 10, 15, 20, 25, 30]
after clear(): []


Updating elements into list

In [12]:
new1 = [5,10,15,20,25,30]
new1[1] = 45
new1[5] = 50
print(new1)

[5, 45, 15, 20, 25, 50]


Removing elements from list.

1. remove()

2. pop()

3. del statement

In [ ]:
new2 = [10,20,30,40,50]
new2.remove(30)
print("after remove(30):", new2)

popped_val = new2.pop(1)
print("after pop(1):", new2)
print("popped value:", popped_val)

del new2[0]
print("after del new2[0]:", new2)

after remove(30): [10, 20, 40, 50]
after pop(1): [10, 40, 50]
popped value: 20
after del new2[0]: [40, 50]


Iterating over lists

In [14]:
a_iter = ['dush', 'bonthu', 'meta', 'c++', 'rust']
for item in a_iter:
  print(item)

dush
bonthu
meta
c++
rust


In [ ]:
# using for loop and in keyword

a2 = [1,3,5,7,9,11]
for value in a2:
  print(value)

1
3
5
7
9
11


In [ ]:
# while loop

a3 = [1,3,5,7,9]
i = 0 # i = 1
while i < len(a3): # 1 < 5
  print(a3[i]) # a3[1] # 3
  i += 1 # increment i.e i = i + 1

1
3
5
7
9


In [15]:
# using enumerate

a4 = [1,3,5,7,9, 11, 13, 15]
for index, value in enumerate(a4):
  print(index, value)

0 1
1 3
2 5
3 7
4 9
5 11
6 13
7 15


In [18]:
# other alternative to enumerate
a44 = [1,3,5,7,9, 11, 13, 15]

for i in range(len(a44)):
    print(i, a44[i])

0 1
1 3
2 5
3 7
4 9
5 11
6 13
7 15


In [19]:
# using list comprehension

a5 = [1,3,5,7,9,11]
[print(value) for value in a5]

1
3
5
7
9
11


[None, None, None, None, None, None]

In [ ]:
# using for loop with range()

a6 = [1,3,5,7,9,11]

n = len(a6)
for i in range(n):
  print(a6[i])

1
3
5
7
9
11


Nested Lists

In [20]:
matrix = [[1,2,3], # col 1
          [4,5,6], # col 2
          [7,8,9]] # col 3
print(matrix[1][2])
print(matrix[2][1])

# row 1 --> 1, 4, 7
# row 2 --> 2, 5, 8
# row 3 --> 3, 6, 9
# matrix[1] = 1, 4, 7
# matrix[2] col2 = 4, 5, 6

6
8


In [ ]:
m = [[1,2,3],[4,5,6], [7,8,9]]
print(m)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [ ]:
# creating multidim list

m1 = [[2,4,6,8,10],
     [3,6,9,12,15],
     [4,8,12,16,20]]
print(m1)

[[2, 4, 6, 8, 10], [3, 6, 9, 12, 15], [4, 8, 12, 16, 20]]


In [ ]:
# creating a multi dim zero matrix

m, n = 4,5
mat = [[0] * n for _ in range(m)]
print(mat)

[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]


In [ ]:
# numpy for performance way

import numpy as np

m, n = 4,5
mat1 = np.zeros((m,n), dtype = int)
print(mat1)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [ ]:
# avoid this trap
# DO NOT DO THIS

mat3 = [[0] * n] * m
mat3[0][0] = 1
print(mat3)

[[1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0]]


Accessing a multi dim list

In [ ]:
# using row-by-row loop

mat7 = [[2, 4, 6, 8, 10], [3, 6, 9, 12, 15], [4, 8, 12, 16, 20]]
for row in mat7:
    print(row)

[2, 4, 6, 8, 10]
[3, 6, 9, 12, 15]
[4, 8, 12, 16, 20]


In [ ]:
# uisng index based nested loops

# 1. The Pythonic Loop (Direct Iteration)

aq = [[2, 4, 6, 8],
     [1, 3, 5, 7],
     [8, 6, 4, 2],
     [7, 5, 3, 1]]
for row in aq:        # row is [2, 4, 6, 8], etc.
    for val in row:  # val is 2, then 4...
        print(val, end=" ")
    print()

2 4 6 8 
1 3 5 7 
8 6 4 2 
7 5 3 1 


In [ ]:
# 2. Best for Printing

aq = [[2, 4, 6, 8],
     [1, 3, 5, 7],
     [8, 6, 4, 2],
     [7, 5, 3, 1]]
for row in aq:
    print(*row)

2 4 6 8
1 3 5 7
8 6 4 2
7 5 3 1


In [ ]:
# 3. if you need the index for a calculation.

aq = [[2, 4, 6, 8],
     [1, 3, 5, 7],
     [8, 6, 4, 2],
     [7, 5, 3, 1]]
for i in range(len(aq)):
    for j in range(len(aq[i])):
        print(aq[i][j], end=" ")
    print()

2 4 6 8 
1 3 5 7 
8 6 4 2 
7 5 3 1 


Methods on Multidimensional Lists

In [ ]:
# 1. append()

a = [[2,4,6],[3,6,9]]
a.append([5,10,15])
print(a)

[[2, 4, 6], [3, 6, 9], [5, 10, 15]]


In [ ]:
# 2. extend()

a = [[2,4,6],[3,6,9]]
a[0].extend([8,10])
print(a)

[[2, 4, 6, 8, 10], [3, 6, 9]]


In [ ]:
# 3. reverse()

a = [[2,4,6],[3,6,9]]

a[1].reverse()   # reverse second row
print(a)
a.reverse()      # reverse row order
print(a)

[[2, 4, 6], [9, 6, 3]]
[[9, 6, 3], [2, 4, 6]]


In [ ]:
# 4. Using Indexing to Read/Write Element

a = [[1,2],[3,4]]

print(a[0][1])   # read
a[1][0] = 9      # write
print(a)

2
[[1, 2], [9, 4]]


In [ ]:
# 5. Using List Comprehension for Processing Rows

a = [[1, 2, 3], [4, 5, 6]]
b = [[ x*2 for x in row ] for row in a]
print(b)

[[2, 4, 6], [8, 10, 12]]


List Comprehension

In [ ]:
squares = [x**2 for x in range(1, 6)]
print(squares)

[1, 4, 9, 16, 25]


How Python Stores List Elements?

In [ ]:
a = [10, 20, "GfG", 40, True]
print(a)
print(a[0])
print(a[1])
print(a[2])

[10, 20, 'GfG', 40, True]
10
20
GfG


Iterate Over a List of Lists

In [ ]:
# Using itertools.chain() Function

from itertools import chain

a = [[1, 2], [3, 4], [5, 6]]
b = list(chain(*a))
print(b)

[1, 2, 3, 4, 5, 6]


Numpy - Iterating Over Arrays

In [ ]:
import numpy as np

# Create a 1D array
arr = np.array([1, 2, 3, 4, 5])

# Iterate over the array
for ele in arr:
    print(ele)

1
2
3
4
5


In [ ]:
# 2d array

import numpy as np

# Create a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Iterate over rows
for row in arr_2d:
    print(row)

[1 2 3]
[4 5 6]
[7 8 9]


In [ ]:
# For Element-Wise Iteration

import numpy as np

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

for element in arr_2d.flat:
    print(element)

1
2
3
4
5
6
7
8
9


In [ ]:
# Higher-Dimensional Arrays

import numpy as np

# Create a 3D array
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# Iterate over the 3D array
for sub_array in arr_3d:
    print(sub_array)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [ ]:
# Using nditer

import numpy as np

# Using nditer
arr = np.array([[1, 2], [3, 4]])

for element in np.nditer(arr):
    print(element)

1
2
3
4


In [ ]:
import numpy as np

arr = np.array([[1, 2], [3, 4]])

for element in np.nditer(arr, order='F'):
    print(element)

1
3
2
4


In [ ]:
import numpy as np

arr = np.array([[1, 2], [3, 4]])

for element in np.nditer(arr, order='C'):
    print(element)

1
2
3
4


In [ ]:
# Using Enumerate

import numpy as np

# Create a 2D array
arr = np.array([[10, 20], [30, 40]])

# Enumerate through rows
for idx, row in enumerate(arr):
    print(f"Row {idx}: {row}")

Row 0: [10 20]
Row 1: [30 40]


In [ ]:
# Using Broadcasting

import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([[10], [20]])

# Perform a broadcasted addition
for x, y in np.nditer([arr1, arr2]):
    print(f"{x} + {y} = {x + y}")

1 + 10 = 11
2 + 10 = 12
3 + 10 = 13
1 + 20 = 21
2 + 20 = 22
3 + 20 = 23


Iterate over Multiple Lists Simultaneously

In [1]:
import itertools

num = [1, 2, 3]
color = ['red', 'white', 'black']
value = [255, 256]

for a, b, c in zip(num, color, value):
    print(a, b, c)

1 red 255
2 white 256


In [2]:
# Using itertools.zip_longest()

import itertools

num = [1, 2, 3]
col = ['red', 'white', 'black']
val = [255, 256]

for a, b, c in itertools.zip_longest(num, col, val):
    print(a, b, c)

1 red 255
2 white 256
3 black None


In [3]:
# Using itertools.zip_longest() with fillvalue

import itertools

num = [1, 2, 3]
col = ['red', 'white', 'black']
val = [255, 256]

for a, b, c in itertools.zip_longest(num, col, val, fillvalue=-1):
    print(a, b, c)

1 red 255
2 white 256
3 black -1
